# Generated by Django 4.1.1 on 2022-10-10 18:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bmstu_lab', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Events1',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_title', models.CharField(max_length=100)),
                ('description', models.CharField(max_length=255)),
                ('img', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'events',
                'managed': False,
            },
        ),
    ]
