# Generated by Django 4.1.1 on 2022-10-10 18:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bmstu_lab', '0002_events1'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Events',
        ),
    ]
