# Generated by Django 4.1.1 on 2022-10-10 18:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bmstu_lab', '0004_events'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Events1',
        ),
    ]
